site:
  title: ownCloud Documentation
  url: http://localhost:5000

content:
  sources:
  - url: .
    branches: HEAD
  - url: https://github.com/owncloud/android.git
    branches:
    - master-antora
    start_path: docs/
  - url: https://github.com/owncloud/ios.git
    branches:
    - master-antora
    start_path: docs/
  - url: https://github.com/owncloud/client.git
    branches:
    - master-antora
    start_path: docs/

ui:
  bundle:
    url: https://github.com/owncloud/docs-ui/releases/download/1.1.0/ui-bundle.zip
  output_dir: assets

output:
  clean: true
  dir: public
